### ISSUE TITLE
Opcja wyboru wariantu kolorystycznego dla logotypów

### ISSUE THREAD

**Issue by bkostrowiecki** [pay-now/paynow-woocommerce#106]
Dobry,

jeśli motyw strony jest ciemny, to niestety przy wybieraniu rodzaju płatności logotypy banków i usług są niewidoczne. Przydałaby się możliwość ustawienia wariantów kolorystycznych dla logotypów, aby były również widoczne na ciemnych tłach.

W załączniku prezentacja:
<img width="539" alt="Zrzut ekranu 2021-07-1 o 14 18 17" src="https://user-images.githubusercontent.com/9528111/124123205-4fd11d00-da77-11eb-805c-2a3321107d3e.png">

Potraktujcie to proszę jako feature request :)

**Comment by michalskladanowski** [comment]
Dzień dobry,
aby dodać tło do kafelków z logami banków może Pan dodać poniższe style:
`.paynow-payment-option-pbl {
    background-color: white;
}`

aby pod logo paynow również było białe tło:
`
.payment_method_pay_by_paynow_pl_pbl > label > img {
    background-color: white;
}
`

**Comment by bkostrowiecki** [comment]
Cześć,

nie jest to niestety najestetyczniejsze rozwiązanie dla stron o ciemnych motywach, muszę przyznać.

Jednak w miarę ok efekty daje coś takiego:
```
.paynow-payment-option-pbl > label { background-color: #bebebe; }

.payment_method_pay_by_paynow_pl_pbl > label > img { background-color: #fff; }

.payment_method_pay_by_paynow_pl_card > label > img { background-color: #fff; }
```
