### ISSUE TITLE
Błędy PHP po ostatniej aktualizacji (2.2.11)

### ISSUE THREAD

**Issue by dziudek** [pay-now/paynow-woocommerce#120]
Po aktualizacji wtyczki na stronie klienta z wersji 2.2.10 do 2.2.11, zaobserwowałem pojawienie się logów typu **fatal-errors-DATA-XYZ.log**.

Wygląda na to, że obsługa wyjątków jest niepoprawna - przykładowy błąd:

```
2021-09-01T19:20:49+00:00 CRITICAL Uncaught Error: Wrong parameters for Exception([string $message [, long $code [, Throwable $previous = NULL]]]) in /***/public_html/wp-content/plugins/pay-by-paynow-pl/includes/class-wc-pay-by-paynow-pl-notification-handler.php:93
Stack trace:
#0 /***/public_html/wp-content/plugins/pay-by-paynow-pl/includes/class-wc-pay-by-paynow-pl-notification-handler.php(93): Exception->__construct('Order status tr...', Array)
#1 /***/public_html/wp-content/plugins/pay-by-paynow-pl/includes/class-wc-pay-by-paynow-pl-notification-handler.php(58): WC_Gateway_Pay_By_Paynow_PL_Notification_Handler->process_notification(Object(Automattic\WooCommerce\Admin\Overrides\Order), Array)
#2 /***/public_html/wp-includes/class-wp-hook.php(303): WC_Gateway_Pay_By_Paynow_PL_Notification_Handler->handle_notification('')
#3 /***/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#4 /***/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array) w /***/public_html/wp-content/plugins/pay-by-paynow-pl/includes/class-wc-pay-by-paynow-pl-notification-handler.php w linii 93
```

Błędy te pojawiają się z pewną regularnością - pojawiły się:

**30 sierpnia:**
* 11:23:35
* 11:24:37
* 11:25:22
* 11:26:23
* 11:27:26
* 11:28:27
* 11:30:28
* 11:35:30
* 11:50:32

I potem już regularnie i dużo rzadziej:
* 12:20
* 13:20
* 15:20
* 19:20

**31 sierpnia**
* 3:20
* 19:20

**1 września**
* 19:20

Z mojej perspektywy wygląda to tak jakby to były jakieś zewnętrzne zapytania przychodzące z bramki PayNow w formacie nieobsługiwanym przez nową wersję wtyczki.

Dodam, że godziny błędów nie pokrywają się z płatnościami. Znalazłem też ukończoną płatność poprzez bramkę, także raczej są to błędy niezwiązane z obsługą płatności.

Na wszelki wypadek na ten moment przywróciłem na stronie klienta wersję 2.2.10, która powyższego błędu nie miała.

W obu wypadkach (wersja 2.2.11 oraz 2.2.10) podczas zakupu testowego byłem poprawnie przekierowywany na stronę bramki płatności (samego zakupu nie finalizowałem). Podczas testów nie pojawiły się żadne nowe logi błędów.

**Comment by michalskladanowski** [comment]
Dziękujemy za zgłoszenie błędu, wypuściliśmy nową wersję wtyczki zawierającą poprawkę: https://github.com/pay-now/paynow-woocommerce/releases/tag/2.2.12

**Comment by dziudek** [comment]
Bardzo dziękuję za szybką reakcję - zainstaluję dzisiaj u klienta nową wersję wtyczki i będę obserwować czy wszystko jest ok. Wątek zamykam - gdyby coś jeszcze się w tym temacie pojawiło - otworzę wątek ponownie :)
