### ISSUE TITLE
Uncaught TypeError: Return value of WC_Gateway_Pay_By_Paynow_PL

### ISSUE THREAD

**Issue by ojdas** [pay-now/paynow-woocommerce#151]
Wersja WP 5.8.2, wersja plugin'a 2.4.4

`Fatal error: Uncaught TypeError: Return value of WC_Gateway_Pay_By_Paynow_PL::get_only_payment_methods_for_type() must be of the type array, null returned in /wp-content/plugins/pay-by-paynow-pl/includes/abstract/class-wc-gateway-pay-by-paynow-pl.php:536 Stack trace: #0 /wp-content/plugins/pay-by-paynow-pl/includes/abstract/class-wc-gateway-pay-by-paynow-pl.php(328): WC_Gateway_Pay_By_Paynow_PL->get_only_payment_methods_for_type('BLIK') #1 /wp-content/plugins/pay-by-paynow-pl/includes/gateways/class-wc-payment-gateway-pay-by-paynow-pl-blik.php(62): WC_Gateway_Pay_By_Paynow_PL->is_payment_method_available('BLIK') #2 /wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(154): WC_Payment_Gateway_Pay_By_Paynow_PL_Blik->is_available() #3 /wp-content/plugins/woocommerce/includes/wc-template-functions.php(3820): WC_Payment_Gateways->get_available_payment_gateways() #4 /wp-includes/class-wp-hook.php(303): wc_get_pay_buttons('') #5 /wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array) #6 /wp-inclu in /wp-content/plugins/pay-by-paynow-pl/includes/abstract/class-wc-gateway-pay-by-paynow-pl.php on line 536`

**Comment by emilleszczak2** [comment]
@ojdas Czy do wtyczki były dodane klucze dostępu ?

**Comment by ojdas** [comment]
@emilleszczak2  Nie, nie ma kluczy.

**Comment by emilleszczak2** [comment]
@ojdas Poprawiona wtyczka https://github.com/pay-now/paynow-woocommerce/releases/tag/2.4.5
