### ISSUE TITLE
Podstrona - /potwierdz-platnosc-blikiem-w-aplikacji-bankowej/

### ISSUE THREAD

**Issue by rafaljosko** [pay-now/paynow-woocommerce#153]
Hej,
Czy podstrona utworzona podczas ostatnich aktualizacji może zostać usunięta? 

 /potwierdz-platnosc-blikiem-w-aplikacji-bankowej/

Tam jest widoczny shortcode [pay_by_paynow_pl_content]

Czy po ostatnich aktualizacjach można ją usunąć z wp

**Comment by emilleszczak2** [comment]
@rafaljosko tak, nie jest już potrzebna.
