### ISSUE TITLE
Błąd krytyczny w logach

### ISSUE THREAD

**Issue by dziudek** [pay-now/paynow-woocommerce#154]
Kilka dni temu oraz dzisiaj zaobserwowałem w logach taki błąd:

```
CRITICAL Uncaught Error: Call to a member function get() on null in /****/wp-content/plugins/pay-by-paynow-pl/includes/class-paynow-gateway.php:187
Stack trace:
#0 /****/wp-content/plugins/pay-by-paynow-pl/includes/abstract/class-wc-gateway-pay-by-paynow-pl.php(530): Paynow_Gateway->payment_methods()
#1 /****/wp-content/plugins/pay-by-paynow-pl/includes/abstract/class-wc-gateway-pay-by-paynow-pl.php(328): WC_Gateway_Pay_By_Paynow_PL->get_only_payment_methods_for_type('BLIK')
#2 /****/wp-content/plugins/pay-by-paynow-pl/includes/gateways/class-wc-payment-gateway-pay-by-paynow-pl-blik.php(62): WC_Gateway_Pay_By_Paynow_PL->is_payment_method_available('BLIK')
#3 /****/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(154): WC_Payment_Gateway_Pay_By_Paynow_PL_Blik->is_available()
#4 /****/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/OnboardingTasks/Tasks w /****/wp-content/plugins/pay-by-paynow-pl/includes/class-paynow-gateway.php w linii 187
```

Wcześniej nie obserwowałem tego błędu. Czy to coś poważnego?

**Comment by emilleszczak2** [comment]
@dziudek dla jakiej strony  to się pojawia? Jesteś w stanie to powtórzyć?

**Comment by dziudek** [comment]
@emilleszczak2 - przejrzałem logi i jedyne co można z nich wywnioskować to to, że najprawdopodobniej błędy te pojawiły się w czasie jak ktoś był w panelu administratora na stronach konkretnych zamówień. W czasie gdy wystąpiły błędy nie znalazłem żadnych requestów po froncie, cały ruch odbywał się w panelu admina. Możliwe, że zamówienia były edytowane i to spowodowało pojawienie się tych błędów. Otwierałem powiązane podstrony, ale od samego otwarcia błąd się nie pojawia.

**Comment by emilleszczak2** [comment]
@dziudek dzięki, przyjrzę się temu i wystawię ewentualną poprawkę.

**Comment by KrisMPL** [comment]
U mnie pojawia się w zasadzie to samo. Można powiedzieć, że około 200 błędów za wczoraj, czyli 14.01.2022

**Comment by dziudek** [comment]
U mnie ten błąd pojawił się od czasu zgłoszenia tego błędu tylko raz - raczej nie jest to powiązane ze składaniem zamówień, bo tutaj nie zaobserwowałem problemów i zgłoszeń od klienta.

**Comment by emilleszczak2** [comment]
Mamy namierzone, będzie nowa wersja w poniedziałek. Problem nie tylko dotykał podglądu zamówienia, ale też innych strony w adminie.

**Comment by emilleszczak2** [comment]
@dziudek Wystawiliśmy nową wersje, powinna rozwiązać problem logów: https://github.com/pay-now/paynow-woocommerce/releases/tag/2.4.6

**Comment by dziudek** [comment]
@emilleszczak2 - dziękuję - zainstalowałem i problem moim zdaniem zniknął. Zauważyłem dzisiaj, że wyświetlenie listy zamówień w panelu powodowało pojawienie się tych logów, natomiast po instalacji wersji 2.4.6, nie pojawiają się nowe błędy w logach. Według mnie wątek do zamknięcia :)

**Comment by KrisMPL** [comment]
@emilleszczak2  - zainstalowane. Potwierdzam, że problem logów został rozwiązany.
