### ISSUE TITLE
Zwroty przez API przechodzą bez błędu mimo braku środków

### ISSUE THREAD

**Issue by PiotrCzapla** [pay-now/paynow-woocommerce#156]
Mamy system który korzysta z API woocommerce do robienia zwrotów automatycznych na podstawie wystawionych faktur korekt.
Pracownik dostaje listę takich korekt i robi zwrot za zwrotem w wypadku paynow/stripe jednym kliknięciem zamieniając fakture korygującą na korespondujący zwrot w woocommerce.

Niestety ostatni zmiana w paynow spowodowała problemy które dopiero teraz zauważyliśmy. Otóż jak nie ma wystarczającej ilości gotówki na koncie kartowym lub paynow, to zwrot przechodzi bez błędu w API. Wcześniej taki zwrot nie przechodził i pracownik wiedział że ma zrobić zwrot manualny na konto klienta lub korzystając z interfejsu paynow.

Poporzednie wersje Paynow jak również Stripe, działają w ten spób że w wypadku błedu podczas zwrotu, ten błąd zwracany jest po API a sam zwrot nie jest tworzony. Czy możemy jakoś przywrócić tą funkcjonalność? 

Teraz lecimy przez arkusz z długą listą zwrotów i próbujemy to jakoś naprawić ręczenie ale chcielibyśmy móc ufać paynow które jak tworzy zwrot z automatyczną zapłatą to ten zwrot jest wykonany.

Możliwe że widzimy problem dopiero teraz bo  cześciej paynow jest wyzerowany.

**Comment by emilleszczak2** [comment]
@PiotrCzapla korzystacie ze standardowego zwrotu w WooCommerce ?

**Comment by PiotrCzapla** [comment]
Tak przez rest APi tworzenie automatycznego zwrotu.

**Comment by emilleszczak2** [comment]
@PiotrCzapla Co w logach macie ?

**Comment by PiotrCzapla** [comment]
Nie widziałem zdjęcia, w mailu i nie zrozumiałem pytania, sorry. 

Z tego co się dowiedziałem to jednak była jedna taka transakcja w której zwrot powstał,,mimo ze powinno go zablokować z info o niewystarczającej ilości środków na koncie. 

Co ciekawe zwrot ze strony paynow wygenerował kolejny raz ten komunikat mimo że tym razem przeszedł ze środków na konice powiązanym. 

Cała sytuacja wyglada tak:

- 23 grudnia o 15:15 mamy komunikat o nie wystarczającej ilości kasy w zam. oraz zwrot utworzony.
- w tym okresie nie ma zwrotu w  serwise transakcyjnym paynow.
Stąd wnioskuje że zwrot przez api przeszedł bez komunikatu o blędzie, bo jak byśmy otym się dowiedzieli w gurniu to zrobilibyśmy ten zwrot manualnie przez system transakcyjny paynow (wybierajać zwrot ze środków przypisanego konta).

Dopiero 13 stycznia dostaliśmy zapytanie od klienta czemu nie dostał kasy. Wtedy też zrobiliśmy zwrot. Co ciekawe kolejny raz pojawiła się informacja o braku środków, mimo że zwrot był robiony przez serwis tranzakcyjny.

Tak to w logach wygląda:
```
2021-12-23T14:15:25+00:00 DEBUG Processing refund request {orderId=NUMER_ZAM, paymentId=ID_TRANSAKCJI_PODAM_W_MAILU, amount=29.00}
2021-12-23T14:15:26+00:00 ERROR INSUFFICIENT_BALANCE_FUNDS - Insufficient funds on balance {orderId=NUMER_ZAM, paymentId=ID_TRANSAKCJI_PODAM_W_MAILU}
2022-01-13T09:46:11+00:00 DEBUG Processing refund request {orderId=NUMER_ZAM, paymentId=ID_TRANSAKCJI_PODAM_W_MAILU, amount=29.00}
2022-01-13T09:46:12+00:00 ERROR INSUFFICIENT_BALANCE_FUNDS - Insufficient funds on balance {orderId=NUMER_ZAM, paymentId=ID_TRANSAKCJI_PODAM_W_MAILU}
```
Jak potrzebujecie numer zam i numer płatności to prosze o maila. Płatność za zamówienie była Blikiem .
