### ISSUE TITLE
BLIK rzuca fatal error

### ISSUE THREAD

**Issue by gmalinowski** [pay-now/paynow-woocommerce#158]
Uncaught Error: Call to undefined method Paynow\Model\PaymentMethods\PaymentMethod::getAuthorizationType() in /wp-content/plugins/pay-by-paynow-pl/includes/gateways/class-wc-payment-gateway-pay-by-paynow-pl-blik.php:53

**Comment by gmalinowski** [comment]
1. Po downgradzie do 2.3.1 problem zniknął.
2. Pojawił się kolejny problem - powrót do sklepu po płatności:
```
Fatal error: Uncaught Error: Undefined constant Paynow\Model\Payment\Status::STATUS_ABANDONED in wp-content/plugins/pay-by-paynow-pl/includes/abstract/abstract-wc-gateway-pay-by-paynow-pl.php:383 Stack trace: #0 wp-content/plugins/pay-by-paynow-pl/includes/abstract/abstract-wc-gateway-pay-by-paynow-pl.php(301): WC_Gateway_Pay_By_Paynow_PL::is_correct_status() #1 wp-content/plugins/pay-by-paynow-pl/includes/abstract/abstract-wc-gateway-pay-by-paynow-pl.php(422): WC_Gateway_Pay_By_Paynow_PL->process_order_status_change() #2 wp-includes/class-wp-hook.php(303): WC_Gateway_Pay_By_Paynow_PL->redirect_order_received_page() #3 wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() #4 wp-includes/plugin.php(470): WP_Hook->do_action() #5 wp-includes/template-loader.php(13): do_action() #6 wp-blog-header.php(19): require_once('...') #7 index.php(17): require('...') #8 {main} thrown in wp-content/plugins/pay-by-paynow-pl/includes/abstract/abstract-wc-gateway-pay-by-paynow-pl.php on line 383
```
3. Po downgradzie do 2.2.13 - wszystko działa.

**Comment by emilleszczak2** [comment]
@gmalinowski zalecam pobranie najnowszej wersji wtyczki. Sprawdziłem i zawiera wszystko co jest potrzebne do jej działania.

**Comment by gmalinowski** [comment]
@emilleszczak2 najnowsza była zainstalowana (v2.4.6) - nie działa. Jedynie wersja 2.2 działa. Czyli wygląda na to, że to u nas jest coś nie tak. Będę miał czas to prześledzę co jest powodem tych błędów.
