### ISSUE TITLE
BLIK - zniknęła możliwość wprowadzenia kodu bezpośrednio na stronie zakupu

### ISSUE THREAD

**Issue by dziudek** [pay-now/paynow-woocommerce#159]
Zauważyłem dzisiaj, że na stronie składania zamówienia po wybraniu BLIK-a jako metody płatności nie ma pól na wpisanie kodu - a jakiś czas temu jeszcze były.

Żadne ustawienia bramek płatności nie były ostatnio zmieniane.

Strona używa WooCommerce 6.1.1, WP 5.8.3 oraz wtyczki PayNow w wersji 2.4.6

Co może być przyczyną takiej zmiany? Nie widzę opcji pozwalających takie zachowanie wtyczki włączyć/wyłączyć

**Comment by emilleszczak2** [comment]
Wczorajsza awaria u jednego z dostawców metod płatności spowodowała wyłączenie możliwości podania kodu na stronie sklepu. Funkcja powinna być już ponownie widoczna w sklepie.
