### ISSUE TITLE
Warningi

### ISSUE THREAD

**Issue by dziudek** [pay-now/paynow-woocommerce#160]
Już trochę tradycyjnie powracam z tematem warningów w logach :) 

Od wczoraj pojawiają się w logach dwie linijki (notice i warning):

```
PHP Notice:  Undefined index: trash in /.../public_html/wp-content/plugins/pay-by-paynow-pl/includes/abstract/class-wc-gateway-pay-by-paynow-pl.php on line 422
PHP Warning:  in_array() expects parameter 2 to be array, null given in /.../public_html/wp-content/plugins/pay-by-paynow-pl/includes/abstract/class-wc-gateway-pay-by-paynow-pl.php on line 422
```

Co ciekawe - wcześniej ich nie było a wtyczka ostatni raz była aktualizowana 17. stycznia do wersji 2.4.6

**Comment by emilleszczak2** [comment]
Z kiedy i z jakiej wersji są te logi, bo nie wygląda na najnowszą?

**Comment by dziudek** [comment]
@emilleszczak2 - to tak jak napisałem - wersja 2.4.6. Same logi zaczęły się pojawiać od 28. stycznia i codziennie do dzisiaj dzisiaj widzę się pojawiają.

Wcześniej widzę były między 7. a 11. stycznia - tylko w linijce 412 a nie 422 w tych samym pliku - w tym poprzednim miejscu widzę pojawiały się nawet wcześniej bo od 31. grudnia. 

A jak tak patrzę to ogólnie ten kod chyba był też w innych plikach bo fragment `Undefined index: trash ` widzę nawet w sierpniu 2021 i pojawiało się co jakiś czas.

**Comment by dziudek** [comment]
@emilleszczak2 - na razie wątek zamykam, otworzę jeśli problem powróci
