### ISSUE TITLE
Wtyczka powoduje timeout w koszyku i nie tylko

### ISSUE THREAD

**Issue by pshemek** [pay-now/paynow-woocommerce#164]
Mam taki problem od paru dni, że strona zawiesza się (timeout) w sytuacjach:
1. Koszyk z produktem
2. Zamówienie
3. Zapis opcji wtyczki Paynow (opcje są zapisane w bazie ale przeładowanie strony kończy timeout)

Problem występuje także gdy metody płatności od Paynow są wyłączone, a ustępuje po deaktywacji wtyczki.
Wygląda jakby wtyczka inicjowała komunikację w tle, nie dostawała odpowiedzi i tkwiła w tym stanie.

Dzieje się to na serwerze produkcyjnym używającym Cloudflare.

Czy mieliby Panowie jakieś tropy/sugestie?

```
2022-03-11T09:55:53+00:00 INFO Retrieving payment methods {currency=PLN, amount=5000}
2022-03-11T09:58:10+00:00 ERROR Operation timed out after 300351 milliseconds with 0 out of 0 bytes received
```

**Comment by emilleszczak2** [comment]
@pshemek Czy połączenie z serwera do api.paynow.pl jest realizowane bez problemów?

**Comment by emilleszczak2** [comment]
@pshemek jak rozwiązuje domene na IP?
można sprawdzić poleceniem
`dig api.paynow.pl A`

**Comment by pshemek** [comment]
`api.paynow.pl.		60	IN	A	20.71.11.216`

**Comment by emilleszczak2** [comment]
@pshemek Jeśli hosting jest na cyber_Folks, to mamy namierzony u nich problem. Pracują nad jego rozwiązaniem

**Comment by pshemek** [comment]
Zgadza się, dziękuję bardzo za wiadomość!

**Comment by emilleszczak2** [comment]
Mam informację, że problem rozwiązany.
