### ISSUE TITLE
blik nie działa losowo

### ISSUE THREAD

**Issue by PiotrCzapla** [pay-now/paynow-woocommerce#165]
Dostaje info ze nie podałem kodu blik mimo ze jest podany :(
<img width="1272" alt="Screenshot 2022-04-06 at 12 36 06" src="https://user-images.githubusercontent.com/340180/161956774-bf3980f4-0105-4fee-8d98-b8932caf4cfa.png">

**Comment by PiotrCzapla** [comment]
Jeszcze chwile temu wszystko działało, klienci płacili blikiem.

**Comment by emilleszczak2** [comment]
@PiotrCzapla Do analizy tego przypadku potrzebuję logów z wtyczki, koniecznie externalId.

**Comment by PiotrCzapla** [comment]
@emilleszczak2 jak ci to wysłać prywatnie?

**Comment by PiotrCzapla** [comment]
w logach nie widze tej tranzakcj wcale, co gorsza jak wylaczylem i wlaczylem  blik to mizaczelo dzialac :(

**Comment by PiotrCzapla** [comment]
oo mam, to sie pojawia jak blik jest pierwsz płatnościa i jest otwarty przy przechodzeniu do checkoutu

**Comment by PiotrCzapla** [comment]
zmakniecie i otworzenie platnosci blik naprawia problem.

**Comment by PiotrCzapla** [comment]
a nie niestety, zamkniecie  wybranie szybkiego transferu i ponowne otwarcie blik i wpisanie nazwy
nie zmienia wiele, zamowienie przechodzi bo wysyla mnie do paynow szybki transfer :(

**Comment by PiotrCzapla** [comment]
zapytanie POST do wc-ajax: checkout niczym się nie różnią.  w obu wypadkach kod blik jest przesylany jako authorizationCode.

Jak blik jest na pierwszym miejscu to sie wywala inforamcja ze nie ma kodu blik jak jest na drugim miejscu to działa.

**Comment by PiotrCzapla** [comment]
A teraz działa bez problemowo :( nawet jak jest piewszy w kolejności.

**Comment by PiotrCzapla** [comment]
z tego co widze to ten fragment nie przechodzi
```
if ( $blik_payment_methods 

&& $this->isWhiteLabelEnabled( $blik_payment_methods ) 
&& ( empty( $payment_authorization_code ) || 
strlen( $payment_authorization_code ) !== 6 ) 
) {
			wc_add_notice( __( 'Please enter correct BLIK code', 'pay-by-paynow-pl' ), 'error' );

			return false;
		}
```
Problem pojawia się przez konwersje do (int)  w pierwszej lini potem wywala sie to sprawdzenie jak kod blik ma 0 na przodzie:
 `strlen( $payment_authorization_code ) !== 6 )`
<img width="553" alt="Screenshot 2022-04-06 at 13 56 20" src="https://user-images.githubusercontent.com/340180/161970009-5757
<img width="215" alt="Screenshot 2022-04-06 at 13 56 43" src="https://user-images.githubusercontent.com/340180/161970019-c5dce4ef-e876-4330-9e21-596d3c9132fe.png">
caca-5dfc-4f9a-b524-042c0fc018c3.png">
<img width="443" alt="Screenshot 2022-04-06 at 13 56 58" src="https://user-images.githubusercontent.com/340180/161970029-50955a32-a6d2-4675-99cf-89a0fffb2074.png">

**Comment by emilleszczak2** [comment]
@PiotrCzapla jak usuniesz tego inta to działa?
```
$payment_authorization_code = preg_replace( '/\s+/', '', filter_input( INPUT_POST, 'authorizationCode' ) );
```

**Comment by emilleszczak2** [comment]
Zaraz będzie poprawka https://github.com/pay-now/paynow-woocommerce/pull/168
