### ISSUE TITLE
Wtyczka zostala usunieta ze sklepu wordpress'a

### ISSUE THREAD

**Issue by PiotrCzapla** [pay-now/paynow-woocommerce#182]
Cześć, wordfence przedstawilo was jako krytyczny blad, bo wtyczka zostala usunieta z katalogu wordpresa. Czy to jest jakis tymczasowy błąd, czy się wycofujecie z hostowania automatycznych upgradow tam?

Problem jest o tyle powżny że teraz ktoś może wydać paynow w wersji malware i automatycznie zainstalować się na moich serwerach stagingowych. :(

**Comment by emilleszczak2** [comment]
Nie wycofujemy się, wtyczka została automatycznie wyłączona. Zgłosiliśmy już ten temat do Wordpressa w celu wyjaśnienia.

**Comment by PiotrCzapla** [comment]
Jakieś wieści?

**Comment by emilleszczak2** [comment]
@PiotrCzapla Tak wtyczka wróciła już jakiś czas temu.
