### ISSUE TITLE
Paynow opóźnia mi stronę z produktem o 1.5 sec (Zapytanie do  api.paynow.pl/v2/payments/paymentmethods)

### ISSUE THREAD

**Issue by PiotrCzapla** [pay-now/paynow-woocommerce#190]
Cześć, właśnie google search console, powiedział mi że moja strona zaczęła kuleć (od 25 grudnia), zacząłem szukać i znalazłem call paynow podczas renderowania się strony z produktem. Call jest async ale jako ze wykonuje się prawie na końcu nie wiele to zmienia i strona renderuje mi się o 1.5sec dłużej

Czy moglibyście to przenieść do jakiś cron'a / woo scheduled actions?

Poniżej screenshot z new relica
<img width="1293" alt="Screenshot 2023-01-06 at 18 12 47" src="https://user-images.githubusercontent.com/340180/211063888-968bfc78-aa4f-46df-b134-71842be5ee5e.png">

**Comment by rafwlaz** [comment]
@PiotrCzapla pytanie z innej beczki, w którym miejscu w new relicu jest taki callstack pokazany dla wordpressa?

**Comment by emilleszczak2** [comment]
@PiotrCzapla czy ty masz checkout podpięty bezpośrednio w stronie produktu albo wywołujesz jakieś filtry poza standardem?

**Comment by emilleszczak2** [comment]
@PiotrCzapla jesteś w stanie podać kiedy miałeś takie problemy żebyśmy mogli dokonać analizy po naszej stronie?

**Comment by PiotrCzapla** [comment]
@rafwlaz  Jak spadnie ci apdex poniżej krytycznych wartości new relic zaczyna robić snapshoty i wtedy dostajesz takie stacktrace.

@emilleszczak2  Właśnie tu jest problem, pay now nie działa na stronach produktowych i nie mam filtrów które by to odpalały. Ale naprawiłem cache więc strony produktowe renderują się rzadko i problem przestał mi przeszkadzać.

Jak dostanę kolejny taki staktrace to otworze ten ticket i dam wam znać z dokładną data. 
Napiszcie co będziecie potrzebować żeby to zdiagnozować.
