### ISSUE TITLE
Generowanie linku do płatności EUR kartą

### ISSUE THREAD

**Issue by rafwlaz** [pay-now/paynow-woocommerce#193]
Witam

Sprawa nie dotyczy stricte wtyczki ale nie mogę przebrnąć przez support mailowy gdyż tam ktoś uparcie twierdzi że jest inaczej niż jest faktycznie.

Mianowicie, mam swoją wtyczkę, która korzysta z Waszego API REST czyli robi dokładnie to samo co Wasza wtyczka.
Mam aktywowane płatności kartą w EUR natomiast po wygenerowaniu linku i wpisaniu danych karty już na formatce pojawia się błąd.

Support uparcie twierdzi że blue media nie wspiera takiego rozwiązania jakie posiadam i mam użyć wtyczki oficjalnej i dodać wybór waluty w sklepie.

Nie bardzo rozumiem skąd blue media ma wiedzieć czy link wygenerowała Wasza wtyczka czy moja, gdzie prawidłowo zgodnie z dokumentacją REST API generuję link z walutą EUR i ten link działa ale sama płatność nie przechodzi. 

Skoro opieram się w 100% na dokumentacji i wszystkie płatności w PLN działają a te w EUR nie chcą, gdzie tam zmiana jest tylko waluty w requeście, to nie rozumiem dlaczego support uparcie twierdzi, że takie rozwiązanie nie zadziała.

**Comment by emilleszczak2** [comment]
Dzięki @rafwlaz. Zapoznamy się z Twoim zgłoszeniem i zweryfikujemy zgłoszony problem.

**Comment by rafwlaz** [comment]
@emilleszczak2 dziękuję bardzo bo tracę nadzieję :) 
Podałem nawet prosty przykład. Mam sklep napisany autorsko od zera i nie ma do niego wtyczki, to logicznym jest, że korzystam z API i na jego podstawie generuje link przekierowania itd.
Support uparcie twierdzi że mam mieć wybór waluty w sklepie i Waszą wtyczkę.

Ja po prostu po wykryciu adresu klienta innego niż Polski, chcę udostępnić metodę płatności kartą w EUR gdzie przelicze w tle kurs z PLN na EUR po średnim kursie z NBP i wyślę taki sam request jak wysyłam dla zwykłych płatności, z tym że będzie inna waluta w requeście.

Wcześniej nie dało się w ogóle wygenerować linku i to było zgłoszone do blue media, problem naprawili i link generuje się i przekierowuje prawidłowo do formatki płatności gdzie jest właściwa waluta, kwota itd.

**Comment by emilleszczak2** [comment]
Temat wyjaśniony.
