### ISSUE TITLE
PHP Fatal error w wersji 2.4.15

### ISSUE THREAD

**Issue by adamlachut** [pay-now/paynow-woocommerce#194]
W pliku pay-by-paynow-pl.php wiersz 43:

`require_once WC_PAY_BY_PAYNOW_PL_PLUGIN_FILE_PATH . 'vendor/autoload.php';`

ale w paczce nie ma folderu _vendor_, co powoduje bład krytyczny WP z komunikatami w rodzaju:

`Backend fatal error: PHP Fatal error:  require_once(): Failed opening required '/wp-content/plugins/pay-by-paynow-pl/vendor/autoload.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /wp-content/plugins/pay-by-paynow-pl/pay-by-paynow-pl.php on line 43\n
`

**Comment by rafaljosko** [comment]
Podpinam się to samo :)

**Comment by emilleszczak2** [comment]
Problem rozwiązany w 2.4.16
