### ISSUE TITLE
Nieprawidłowy format inputu do wpisania kodu blik

### ISSUE THREAD

**Issue by RodzynDev** [pay-now/paynow-woocommerce#197]
Cześć,
Macie błąd we wtyczce polegający na spacji w regexie do weryfikacji czy kod blik jest prawidłowy, w pliku templates/blik_payment.phtml

Jest input z regexem: 
`<input autocomplete="off" inputmode="numeric" pattern="[0-9]{3} [0-9]{3}" minlength="6" maxlength="6"
                   id="paynow_blik_code" name="authorizationCode" type="text" value="" class="required form-control"
                   placeholder="___ ___">`
                   
W regexie jest `[0-9]{3} [0-9]{3}` a input ma atrybut `minlength="6" maxlength="6"` więc przeglądarki wyrzucają błąd walidacji pola ;)

**Comment by emilleszczak2** [comment]
@RodzynDev jaka przeglądarka ?

**Comment by RodzynDev** [comment]
@emilleszczak2 
Firefox 110.0 i w górę + najnowszy chrome

**Comment by emilleszczak2** [comment]
Testowałem to na swojej przeglądarce i nie mam tego efektu. Wrzucę to jako temat do ulepszenia.

**Comment by emilleszczak2** [comment]
W kodach źródłowych wtyczki jest już poprawka, zostanie załączona do kolejnej wersji wtyczki.
