### ISSUE TITLE
Macie błąd (Skipped processing. Order not found)

### ISSUE THREAD

**Issue by the-work** [pay-now/paynow-woocommerce#209]
W najnowszej wersji wtyczki jest błąd, który wskazuje w dzienniku woocommerca na:
 _ERROR Skipped processing. Order not found_

Aby go naprawić, należy w pliku:
/includes/abstract/class-wc-gateway-pay-by-paynow-pl.php

**Linia 625:** w  **$this->process_notification** zamienić **$orde**r na **$order_id**
**Linia 378:** zamienić kolejność zmiennych na:
public function process_notification( **$external_id**, **$payment_id**, **$status**,  $modified_at = '', $force = false ) {

**Comment by emilleszczak2** [comment]
Weryfikujemy

**Comment by emilleszczak2** [comment]
@the-work Poprawka naniesiona w najnowszej wersji.
