### ISSUE TITLE
Błąd tłumaczeń PL 

### ISSUE THREAD

**Issue by leszeksledzinski** [pay-now/paynow-woocommerce#217]
Błąd tłumaczeń:
Enter blik code
Read more
Choose bank

![IMG_7310](https://github.com/pay-now/paynow-woocommerce/assets/141518275/92878712-f5f1-4f6a-9856-fc875f2314fc)
![IMG_7312](https://github.com/pay-now/paynow-woocommerce/assets/141518275/81d06cc3-8902-4331-8bd8-47810ecfd883)

**Comment by rafaljosko** [comment]
@emilleszczak2  - Możęcie dodać tłumaczenia - to strasznie zniechęca ludzi do płątności waszą bramką.

**Comment by rafaljosko** [comment]
W waszej wtyczce są nowe tłumaczenia, lecz wcześniej łądowaliście pliki jezykowe do folderu systemowego z WordPress, teraz wgraliście je do folderu wtyczki - pamiętajcie, że tłumaczenia w WordPress są ważniejsze :) Musicie i tam zaktualizować :) 

![image](https://github.com/pay-now/paynow-woocommerce/assets/33252062/20ee793e-8ac1-4694-8c20-7694eab01c99)

**Comment by DeveloperMovecloser** [comment]
@rafaljosko Te rozwiązanie w naszej wtyczce występuje już od dawna, niestety nie rozwiązuje ono problemu. We wtyczce tłumaczenia są aktualne i poprawne, problemem jest to że tłumaczenia pobierane z repozytorium tłumaczeń wordpress mają wyższy priorytet niż tłumaczenia we wtyczce a niestety są niepełne i nieaktualne

**Comment by DeveloperMovecloser** [comment]
@rafaljosko @leszeksledzinski Właśnie wydaliśmy nową wersję 2.4.29, która poprawia kwestię tłumaczeń i wyłącza wymuszenie lokalnej wersji tłumaczeń. Zachęcam do aktualizacji.
