### ISSUE TITLE
Problem z wtyczką w WooCommerce, WPGraphQL oraz WooGraphQL

### ISSUE THREAD

**Issue by Arthur-Sebastian** [pay-now/paynow-woocommerce#218]
Konfiguracja:

Pay by PayNow 2.4.24;
WooGraphQL 0.15.0;
WPGraphQL 1.14.10;
WooCommerce 8.0.0;
Wordpress 6.3;
PHP 8.2.

Opis problemu:

Wtyczka powoduje problemy z pomyślnym zapytaniem do endpointu `/graphql` obsługiwanego przez wtyczkę WPGraphQL generując błąd:
![image](https://github.com/pay-now/paynow-woocommerce/assets/83980223/371097fd-6fc4-468d-a196-ed4970d7e4a3)

Ponadto pojawia się także problem z załadowaniem niektórych widoków panelu administracyjnego Wordpressa, głównie tych od WooCommerce, tutaj strona główna:
![image](https://github.com/pay-now/paynow-woocommerce/assets/83980223/2e2c8b52-ca98-4f8c-a63c-9a7b9e6985ea)

Problem ustępuje po wyłączeniu wtyczki `Pay by PayNow`.

Kroki do odtworzenia:

1. Zainstalować wszystkie wymienione wyżej wtyczki.
2. Otworzyć stronę główną zakładki konfiguracyjnej WooCommerce.
3. Odpytać endpoint `/graphql` za pomocą metody POST o następującym body:
```json
{
  query myQuery {
     paymentGateways {
       nodes {
         id
       }
     }
  }
}
```
4. W odpowiedzi powinien wystąpić błąd ze screenshota powyżej.

**Comment by paynow-support** [comment]
Dzień dobry,

dziękujemy serdecznie za zgłoszenie. Poprawkę zamieściliśmy w release 2.4.25 naszej wtyczki.

https://github.com/pay-now/paynow-woocommerce/releases/tag/2.4.25
