### ISSUE TITLE
Dostępne nowe tłumaczenia po aktualizacji tłumaczeń

### ISSUE THREAD

**Issue by ahabuda** [pay-now/paynow-woocommerce#226]
Siemanko,

Coś nie pykło z nowym update i mimo aktualizacji tłumaczeń wyświetla komunikat, że nowe tłumaczenia są dalej dostępne. I tak w kółko.

https://i.imgur.com/Yx8XgXp.png
https://i.imgur.com/o7qR9MS.png

**Comment by mikex1993** [comment]
Na mojej stronie również ten sam problem.

**Comment by KrzysztofUstowski** [comment]
@mikex1993 @ahabuda w tej wersji wtyczka ignoruje tłumaczenia z globalnego repozytorium tłumaczeń i wykorzystuje wyłącznie własne tłumaczenia lokalne dostarczane w źródłach wtyczki. 

Komunikat, o którym wspominacie, to  komunikat mówiący o tym, że WP widzi nowsze tłumaczenia w repozytorium (nowsze ale błędne) i to właśnie je chce aktualizować. Po aktualizacji, wtyczka i tak wymusza swoje własne tłumaczenia i stąd takie komunikaty.

Jesteśmy w trakcie korekty tłumaczeń w globalnym repozytorium tłumaczeń, jak tylko poprawimy tłumaczenia globalne, to wyłączymy mechanizm wymuszenia lokalnych tłumaczeń. 

Do tego czasu WP będzie Wam mówił, że są nowsze tłumaczenia, ale proszę nie aktualizujcie ich. Tłumaczenia lokalne dostarczane ze źródeł wtyczki są prawidłowe.

**Comment by KrzysztofUstowski** [comment]
Jak tylko uzupełnimy tłumaczenia w globalnym repozytorium, to wydamy kolejną wersję, która przestanie wymuszać lokalne tłumaczenia.

**Comment by DeveloperMovecloser** [comment]
@mikex1993 @ahabuda Właśnie wydaliśmy nową wersję 2.4.29, która poprawia kwestię tłumaczeń i wyłącza wymuszenie lokalnej wersji tłumaczeń. Zachęcam do aktualizacji.
