### ISSUE TITLE
Brak kompatybilności z wtyczką Woocommerce - MailerLite

### ISSUE THREAD

**Issue by innovauno** [pay-now/paynow-woocommerce#25]
Wtyczka Paynow nie ma kompatybilności z Woocommerce MailerLite [https://wordpress.org/plugins/woo-mailerlite/](https://wordpress.org/plugins/woo-mailerlite/) - w momencie uruchomienia jednej z tych dwóch, gdy druga jest aktywna następuje błąd krytyczny PHP.

**Comment by emilleszczak2** [comment]
@innovauno znamy ten problem. Nie jest on spowodowany przez naszą wtyczkę tylko przez woo-mailer-lite, wykorzystują zależności w kodzie które mają błąd https://github.com/mailerlite/woo-mailerlite/issues/26. Zgłosiliśmy to również na ich profilu Githuba. Inni również zgłosili problem z zależnościami https://github.com/mailerlite/mailerlite-api-v2-php-sdk/issues.
Dla naszych Klientów przygotowaliśmy poprawioną wtyczkę woo-mailerlite. W celu jej udostępnienia napisz do nas na support@paynow.pl.
