### ISSUE TITLE
Zduplikowany mail - "Nowe zamówienie".

### ISSUE THREAD

**Issue by DEJVQ** [pay-now/paynow-woocommerce#26]
Po podłączeniu bramki PayNow - przy opłacaniu zamówienia wysyła się zduplikowany email odnośnie realizacji zamówienia "Nowe zamówienie".

Email wysyła się 2 razy:
1 raz - po kliknięciu przycisku "kupuję" w checkoucie Woocommerce (przed przekierowaniem do płatności PayNow),
2 raz - po opłaceniu zamówienia PayNow.

**Comment by emilleszczak2** [comment]
@DEJVQ Dziękujemy za zgłoszenie. Zweryfikujemy je i wrócimy z odpowiednimi akcjami.
