### ISSUE TITLE
Błąd zapisywania konfiguracji wtyczki

### ISSUE THREAD

**Issue by Kosmoski8** [pay-now/paynow-woocommerce#28]
Podczas zapisywania ustawień konfiguracyjnych wtyczki (Klucz API, klucz podpisu) występuje krytyczny błąd. Niezależnie od zaznaczonych opcji czy wpisanych kluczy.
Wersja WooCommerce 4.1.0
Wordpress 5.4.1

> Fatal error: Uncaught Error: Call to undefined function wc_add_notice() in /home/atheron/websites/savoir7.pl/wp-content/plugins/paynow-woocommerce-b79ba07d5add4454c16ce5aa9926da32fb3c32e6/includes/class-wc-gateway-paynow.php:74 Stack trace: #0 /home/atheron/websites/savoir7.pl/wp-includes/class-wp-hook.php(287): WC_Gateway_Paynow->process_admin_options('') #1 /home/atheron/websites/savoir7.pl/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #2 /home/atheron/websites/savoir7.pl/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /home/atheron/websites/savoir7.pl/wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-payment-gateways.php(227): do_action('woocommerce_upd...') #4 /home/atheron/websites/savoir7.pl/wp-includes/class-wp-hook.php(287): WC_Settings_Payment_Gateways->save('') #5 /home/atheron/websites/savoir7.pl/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #6 /home/atheron/websites/savoir7.pl/wp-includes/plugin.php(478): WP_Hook->do_action(Array) in /home/atheron/websites/savoir7.pl/wp-content/plugins/paynow-woocommerce-b79ba07d5add4454c16ce5aa9926da32fb3c32e6/includes/class-wc-gateway-paynow.php on line 74

**Comment by emilleszczak2** [comment]
@Kosmoski8 Czy pobrałeś wersję wtyczki z zakładki https://github.com/pay-now/paynow-woocommerce/releases/latest? Pamiętaj o pobraniu pliku paynow.zip.
