### ISSUE TITLE
Panowie kiedy wersja 1.0.9 ?

### ISSUE THREAD

**Issue by rafaljosko** [pay-now/paynow-woocommerce#30]
Widzę poprawione błędy z mailem,  jeden z zapytaniem ale dalej wersji 1.0.9 brak ?   Możecie dodać jedną cyferkę ?

**Comment by emilleszczak2** [comment]
@rafaljosko Daj nam jeszcze chwilę, pracujemy nad wystawieniem nowej wersji SDK dla naszego API, które chcemy odrazu podpiąć do najnowszej wersji wtyczki dla WooCommerce.

**Comment by emilleszczak2** [comment]
@rafaljosko Nowa wersja wydana.
