### ISSUE TITLE
Problem z zarzadzaniem stanem magazynowym Oczekuje na platnosc - zmniejsza stan

### ISSUE THREAD

**Issue by PiotrCzapla** [pay-now/paynow-woocommerce#33]
Woocomerce ma taki dziwną ceche, zamowienia w trybie "oczekuje na platnosc" maja zarezerwowane produkty na stocku. Stock jest nie zmniejszony ale woocomerce nie pozwala na ich kupno. Wtyczki z platnosciami w woo, czekaja ze zmiana stanu magazynu na to aż zamowienie przejdzie w stan "W realizacji".  Pay now odraz zmniejsza stan. To powoduje że wiszące zamowienie ma zarezerwowane 2 produkty (jeden przez paynow - zdjecie ze stanu, drugi przez woocomerce ta cicha rezerwacja).

To powoduje duże problemy w sklepach z rzadkimi  przedmiotami w ktorych stan magazynowy jest niski.  Jedno wiszące zamowienie w stanie "oczekuje na platność" z rzadkim produktem ktorego mamy 2 egzemplarze przyblokowuje nam ten produkt  na 48h!

Co gorsze ten produkt dalej jest widoczny w sklepie, bo ta rezewacja woocommrece  jest nie widoczna dla klienta i produkt wyswietla sie jako dostepny 1 na stanie, na tomiast proba kupienia go konczy się nie powodzeniem, co bardzo irytuje naszych klientow (mamy pelno chatow z tym zwiazanych).

Stan czeka na płatność został stworzony do płatności kartą w których oczekiwanie nie jest dlugie - maksymalnie pare minut, to jak ten stan jest to uzywany w paynow  jest nie kompatybiliny z woo :( i powoduje problemy. 

Czy możemy coś z tym zrobić?

**Comment by PiotrCzapla** [comment]
Dodaktowo ta zmiana magazynu podczas przejscia w stan "oczekuje na platnosc" nie jest odwarcana gdy zamowienie jest anulowane, co powoduje desynchronoizacje magazynu ze stanem rzeczywistym.

**Comment by PiotrCzapla** [comment]
tu jest opis jak ten mechanizm dziala: https://github.com/woocommerce/woocommerce/issues/20596

**Comment by michalskladanowski** [comment]
Dzień  dobry,
Dziękujemy za zgłoszenie tego błędu. Jesteśmy w trakcie analizowania omawianego przez Pana przypadku nieprawidłowego zachowania naszej wtyczki. Będziemy informowali o ewentualnym terminie wdrożenia poprawki.

**Comment by PiotrCzapla** [comment]
Moge coś pomoć, zalezy mi na tym zeby to fixnac szybko bo na razie recznie poprawiam takie przypadki co jest bardzo uciązliwe. Jak myślałem o tych stanach to stan "oczekjue na platność" jest zupełnie nie przystosowany do obsługi płatności, które  mogę przebywać w stanie oczekuje na płatność dłużej niż pare minut, może zrobić nowy stan podobny do stanu "wstrzymane czeka na platność"  który pojawia się przy płatności przelewem bankowym ?

Ten schemat platnosci jest przystosowany do oczekiwania dluzszego niż pare minut, dodatkowo macie kod jak to jest zaimplementowane w woocomorece wiec to w dużej mierze bedzie copy paste zeby to fixnąc.

**Comment by PiotrCzapla** [comment]
Jakaś szansa na to zeby to ruszyć juz 6 dni minelo, i mam juz caly stan stocka rozwalony przez ta wtyczke.

**Comment by emilleszczak2** [comment]
@PiotrCzapla mamy poprawkę, nowa wersja będzie dzisiaj/jutro.

**Comment by emilleszczak2** [comment]
@PiotrCzapla  https://github.com/pay-now/paynow-woocommerce/releases/tag/v1.0.10

**Comment by PiotrCzapla** [comment]
@emilleszczak2  Ide przez kod i pare spraw mi nie niepokoi
Jest scieżka w ktorej dwa razy robicie increase stock, 
STATUS_NEW 
STATUS_ERROR - (increase stock)
STATUS_REJECTED - (increase stock)

Patrząc na kod woo, to blokada przed podwojnym powiekszeniem stocku nie dziala z uwagi na cos co wyglada na błąd.

Z drugiej strony STATUS_NEW  nie wydaje sie być możliwy do ustawienia, przynajmniej żaden stan zamowienia sie na niego nie mapuje, chyba ze to taki sztuczny stan.


Co dodatkowo mnie martwi to nie widze obsługi manulanego przestawiania zamówienia w Completed albo Canceled, chyba ze to jest obslugiwane przez woo.

**Comment by PiotrCzapla** [comment]
W kadzym razie dziekuje za updated przetestuje u siebie i dam znać jakby ten problem z przejsciem z new -> error -> rejected sie pojawil.

**Comment by emilleszczak2** [comment]
@PiotrCzapla daj znać, testowałem to i wyglądało, że działanie jest poprawnie. Woo samo nie zwiększało stocku przy zmianie stanu na anulowane dlatego dodałem taką funkcjonalność.

Co do STATUS_NEW nie jest on dla Woo potrzebny ze względu na flow Woo.

**Comment by emilleszczak2** [comment]
@PiotrCzapla można zamknąć ?

**Comment by PiotrCzapla** [comment]
nie widzialem komentarza ,sorry. 

Niestety stock dalej jest psuty przez ten plugin. Opisze to moze w nastepnym bugu. Wydaje sie ze woo jednak zwieksza stan  magazynowy jak przechodzi na "anulowane" zamowienie, bo jedno z moich zamowien ktore paynow anulowal zwiekszylo stan magzynowy dwa razy.
