### ISSUE TITLE
Po złożeniu zamówienia i poprawnym opłaceniu status zamówienia nie zmienia się na "W trakcie realizacji"

### ISSUE THREAD

**Issue by wchmiel** [pay-now/paynow-woocommerce#40]
Tak jak w tytule, gdy klient złoży zamówienie i opłaci je poprawnie po przez paynow status zamówienia nie zmienia się z "Oczekujące na płatność" na "W trakcie realizacji". Przez to ani klient ani sprzedawca nie otrzymują potwierdzenia transakcji. Czy trzeba ustawić coś dodatkowo żeby to działało poprawnie (z automatu zmieniało te statusy) czy jest to bug tej wtyczki?

Wersja 1.0.11

**Comment by emilleszczak2** [comment]
@wchmiel Musisz skonfigurować poprawnie adres powiadomień w Panelu Paynow Bankowości internetowej banku.

**Comment by wchmiel** [comment]
Działa, dzięki ;)

Może warto dodać do dokumentacji dodatkowy punkt z krótką informacją, że adres powiadomień jest niezbędny do prawidłowego działania i odpowiedniej zmiany statusów?

**Comment by emilleszczak2** [comment]
Super, że działa!

Wtyczka sama ustawia adres powiadomień. Nie stanie się jednak tak gdy ktoś uruchamia integrację na innym adresie niż podał w umowie.

Jeśli chodzi o dokumentację to wszystko w niej znajdziesz - patrz [FAQ](https://github.com/pay-now/paynow-woocommerce#faq).
