### ISSUE TITLE
Problem po instalacji

### ISSUE THREAD

**Issue by Uente** [pay-now/paynow-woocommerce#41]
Niestety po instalacji pojawia się taki błąd:

Warning: PHP Startup: failed to open stream: No such file or directory in /wp-content/plugins/paynow-woocommerce-master/woocommerce-gateway-paynow.php on line 32

Warning: PHP Startup: Failed opening '/wp-content/plugins/paynow-woocommerce-master/vendor/autoload.php' for inclusion (include_path='.:/:/usr/local/php73/lib/pear') in /wp-content/plugins/paynow-woocommerce-master/woocommerce-gateway-paynow.php on line 32

Fatal error: Uncaught Error: Class 'Paynow\Client' not found in /wp-content/plugins/paynow-woocommerce-master/includes/class-wc-gateway-paynow.php:95 Stack trace: #0 /wp-content/plugins/paynow-woocommerce-master/includes/class-wc-gateway-paynow.php(63): WC_Gateway_Paynow->init_paynow_client() #1 /wp-content/plugins/paynow-woocommerce-master/includes/class-wc-paynow-notification-handler.php(12): WC_Gateway_Paynow->__construct() #2 /wp-content/plugins/paynow-woocommerce-master/includes/class-wc-paynow-notification-handler.php(143): WC_Gateway_Paynow_Notification_Handler->__construct() #3 /wp-content/plugins/paynow-woocommerce-master/woocommerce-gateway-paynow.php(36): include_once('/wp-content/plu...') #4 /wp-includes/class-wp-hook.php(287): woocommerce_gateway_paynow_init('') #5 /wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #6 /wp-includes/plugin.php(478): WP_Hook->do_action(Array) #7 /wp-settings.php(403): do_action('plugins_loaded') #8 /wp-config.php(76): require_once('/wp-settings.ph...') #9 / in /wp-content/plugins/paynow-woocommerce-master/includes/class-wc-gateway-paynow.php on line 95

**Comment by emilleszczak2** [comment]
Problem wynika z zainstalowania wtyczki z kodów źródłowych a nie z wersji zreleasowanych. Wtyczkę należy pobrać ze strony https://github.com/pay-now/paynow-woocommerce/releases/latest - plika paynow.zip .
