### ISSUE TITLE
Problem z odpaleniem wtyczki

### ISSUE THREAD

**Issue by nipnet** [pay-now/paynow-woocommerce#42]
Pobrałem waszą bramkę
Parametry witryny
wp 5.3.4
woo 4.0
mam php 7.3

Przy odpaleniu wtyczki mam biały ekran oraz 
Error thrown
Class 'Paynow\Client' not found

**Comment by emilleszczak2** [comment]
@nipnet Proszę pobrać wtyczkę do instalacji z ostatnich wydań. Plik paynow.zip dostępny tutaj: https://github.com/pay-now/paynow-woocommerce/releases/latest

**Comment by 4tech-wojtek** [comment]
Witam,
u mnie po zainstalowaniu i włączeniu klasyczny:

> `W witrynie wystąpił błąd krytyczny. W wiadomości wysłanej na adres e-mail administratora strony umieszczono dodatkowe instrukcje.`

Parametry witryny
WP: 5.4.2
WC: 4.3.0
PHP: 7.3.19-1+0~20200612.60 + debian9 ~1.gbp6c8fe1
cURL: 7.52.1, OpenSSL/1.0.2u
paynow: 1.0.12

Namierzyłem Error w logach serwera:

> `Got error 'PHP message: PHP Fatal error:  Cannot redeclare Clue\\StreamFilter\\register() (previously declared in /www/robieto/wp-content/plugins/paynow/vendor/clue/stream-filter/src/functions.php:140) in /www/robieto/wp-content/plugins/woo-mailerlite/vendor/clue/stream-filter/src/functions.php on line 127', referer: https://robieto.pl/wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s=`

Czyli w moim przypadku "gryzie się" z inną wtyczką - z MailerLite'a... chyba trzeba będzie zmienić nazwę tej funkcji, albo coś podobnego ;)

Po wyłączeniu wtyczki MailerLite'a - PayNow śmigał prawidłowo, a po włączeniu oczywiście błąd serwera identyczny jak wcześniej...

**Comment by emilleszczak2** [comment]
Mailer lite wystawił nową wtyczkę która rozwiązuje problem po ich stronie.
