### ISSUE TITLE
Brak możliwości zmiany opisu metody płatności

### ISSUE THREAD

**Issue by hohohupi** [pay-now/paynow-woocommerce#48]
Wtyczka nie umożliwia ustawienia własnego opisu metody płatności, który ma ogromne znaczenie przy decydowaniu o wyborze bramki przez Klientów.

Ustawiłem w swoim sklepie Paynow jako pierwszą/domyślną metodę płatności, a mimo to Klienci wybierają P24, które mogę opisać jako "Natychmiastowy przelew online".

Dodanie możliwości ustawienia własnego opisu, byłoby bardzo cenną funkcją.
Załączam jak to wygląda u mnie w sklepie w tej chwili:

![image](https://user-images.githubusercontent.com/65716122/89520424-20218280-d7de-11ea-9feb-5d4897ebdf89.png)

**Comment by emilleszczak2** [comment]
@hohohupi Zmiany możesz dokonać w konfiguracji tłumaczeń dla wtyczki.

**Comment by hohohupi** [comment]
Zmieniłem i działa dziękuję, natomiast możliwość wpisania własnego opisu mogłaby zostać dodana w kolejnej wersji wtyczki.

Pozdrawiam
