### ISSUE TITLE
Paynow anuluje zamowienia ktore są oplacone w inny sposób.

### ISSUE THREAD

**Issue by PiotrCzapla** [pay-now/paynow-woocommerce#50]
Gdy paynow nie zadziała a klient opłaci inaczej zamówienie (np. przelew bankowy czy inny przez innego dostawce platności) zamówienie przechodzi w stan "in progress" i jest realizowane.
Niestety paynow po pewnym czasie (6 dni?) wysyła informacje że zamowienie nie przeszło i anuluje je co powoduje błędy na stocku.
Co gorsze klient dostaje maile ktore moga wygladac dla niego jak losowe.

Dodatkowo widać też tu że "anulowanie zamowienia" powoduje zwiekszenie stocka 2 razy tak jak wspominalem w review do #33, paynow nie powinien manulanie zwiekszać stanu tylko polegać na woo, w ten sposob inne pluginy ktore polegaja na woo (typu stripe) beda dobrze wspolpracowaly i stan magazynowy nie bedzie sie zwiekszal dwa razy przy anulowaniu.

Jak mysle o tym bugu to zrobiłbym zabezpieczenie ze "anulować" można tylko zamówienie które jest w stanie "pending" (oczekuje na platność), a jeżeli juz zostanie przeniesione  w inny stan ("in progres", "complted" czy "canceled") to paynow nie powinien zmieniać jego stanu, w ten sposob unikniemy takiej systuacji jak na ponizszym screenshotcie.
<img width="269" alt="Screenshot 2020-09-14 at 15 59 46" src="https://user-images.githubusercontent.com/340180/93095754-cf862a80-f6a3-11ea-93de-aa0d3eb30b55.png">

**Comment by PiotrCzapla** [comment]
@emilleszczak2 Mieliście okazje zerknąć na tego ticketa?

**Comment by emilleszczak2** [comment]
@PiotrCzapla Jeszcze nie, ale w tym tygodniu powinna być poprawka.

**Comment by emilleszczak2** [comment]
@PiotrCzapla ten screen powyżej tyczy się jednego zamówienia? 

W Paynow jeśli płatność się nie uda to powiadomienie jest wysyłane natychmiast nie po 6 dniach. Podaj proszę numer płatności prześledzimy co się działo.

Zmieniłem flow zamówienia na dokładnie taki sam jak sugeruje dokumentacja WooCommerce, czyli zwiększenie stanu magazynowego poprzez WooCommerce dla akcji anulowania zamówienia przez admina lub Klienta. Zmienly się też statusy pośrednie ale nie mają wpływu na złożone zamówienia.
Poniżej przykład zamówienia z nieudaną płatnością i kolejną udaną.
![Flow](https://i.imgur.com/BmVyVLt.png.

**Comment by emilleszczak2** [comment]
Release [1.0.14](https://github.com/pay-now/paynow-woocommerce/releases/latest)zawiera poprawkę dla operacji na stocku

**Comment by PiotrCzapla** [comment]
@emilleszczak2  napisz do mnie na piotr@jungleboogie.pl to ci wyśle numer transkacji.

**Comment by PiotrCzapla** [comment]
@emilleszczak2  dzieki prawie dziala, dobry pomysl z przechodzeniem na "on-hold", jest tylko jeden bug z tym zwiazany prejscie z on-hold  na failed nie powoduje przywrócenia stanu magazynowego niestety.

**Comment by PiotrCzapla** [comment]
@emilleszczak2  I jeszcze jedna prośba czy można zrobić tak żeby paynow nie anulował zamówień które są juz "completed" lub "in-progress"? Niestety paynow co pewien czas wisi w stanie "oczkuje", teraz w woo to jest on-hold. 

Czasem zirytowany klient płaci przelewem tradycyjnym, wtedy my przełączamy zamowienie w "in-progress", bardzo zależałoby nam aby ono nie zostało anulowane przez paynow jak płatność wygaśnie po waszej stronie.

To jest jeden z tych błędów który mój dział wsparcia cały czas wyciąga jako argument za przejściem na inne płatności

**Comment by emilleszczak2** [comment]
@PiotrCzapla odgrzewam temat...

Jeśli zamówienie jest w statusie `completed` to nie dojdzie do przebicia stanu niższy zgodnie z matrycą https://docs.paynow.pl/paynow-statuses.png

Natomiast jeśli zamówienie jest w statusie `on-hold` dozwolone jest przejście na anulowano lub opłacono zgodnie z dokumentacją WooCommerce.

Zabezpieczenie jakie dodamy to sprawdzenie czy aktualnie wybrana metoda platności to paynow.

**Comment by PiotrCzapla** [comment]
Dzieki! A jak to załatwi problem z zamowieniem ręcznie przełączonym w in-progress jak zirytowany klient płaci przelewem bankowym nie korzystając z paynow? Bo to te zmówienia zostały anulowane :(

Dodatkowo wykryliśmy kolejne problemy ze stockiem, opisze to w kolejnym tickecie.
