### ISSUE TITLE
Nieudane zamowienia sciągają produkt ze stocka nie przywracając ich

### ISSUE THREAD

**Issue by PiotrCzapla** [pay-now/paynow-woocommerce#59]
Witam,
kolejny problem ktory odkryliśmy to zamowienie które jest Nieudane przez paynow sciąga towary z magazynu ale nie zwraca ich po przejściu w stan nieudane.
poniżej log z zamowienia:
<img width="273" alt="Screen Shot 2020-12-06 at 20 41 18" src="https://user-images.githubusercontent.com/340180/101290565-67a73200-3803-11eb-8e47-538943f57830.png">

**Comment by emilleszczak2** [comment]
@PiotrCzapla
Dzięki za zgłoszenie, której wersji plufinu używacie ?

Nasz moduł obecnie nie dotyka stanów magazynowych, zostawia całą logikę dla WooCommerce zgłoszane było to przez Ciebie.

Podaj identyfikator płatności dla tego zamówienia, sprawdzimy logi powiadomień.

Możemy dać możliwość konfiguracji w panelu aby podczas otrzymania informacji o nieudanej autoryzacji bądź błędzie nastąpiła zmiana stocku.

**Comment by PiotrCzapla** [comment]
Mysle że stan Nieudane / Cancelled to jest customowy stan, który nie jest wpełni wspierany przez woo commerce. Jak zamienie to na anulowane to stan poprawnie się przywróci. 

korzystamy z 1.0.14, czyli tej ktora nie zarzadza stanami, ale mysle ze takie stany jak cancelled trzeba ciagle obslugiwac.

**Comment by PiotrCzapla** [comment]
@emilleszczak2  a mozesz mi wysłać maila na piotr@jungleboogie.pl w sprawie identyfikatorow platnosci?

**Comment by PiotrCzapla** [comment]
Wlasnie zobaczylem jak sobie stripe radzi, i on tez ustawia stan na nieudane,  ale przechodzi z pending wiec nie ma stanu. Moze 'canceled' nie obsluguje zmian na stocku tak jak pending? I woo nie wspiera przejscia z onhold -> canceled ?

**Comment by emilleszczak2** [comment]
Dopisaliśmy testowo funkcjonalność, która dla nieudanej płatności zmieni stan magazynowy, niestety ma to swoje konsekwencje. Ponowne udane opłacenie niestety już nie zmieni stanu. Przykład poniżej:
- nieudana płatnośc
- automatyczne przywrócenie stanu
- ponowna płatność
- brak zdjęcia ze stanu

![failed_payments_stock_management](https://user-images.githubusercontent.com/2837751/101747312-ed5d0300-3acb-11eb-9fd7-a5afa7f7abbd.png)

**Comment by PiotrCzapla** [comment]
Nie wiem czy to duzo lepiej bo to mozna jeszcze manualnie poprawic, a overselling powstaly przez nie zdjecie ze stocka duzo gozej sie poprawia bo trzeba dzwonic po klientach.
Ale moze da sie to naprawic.
Jak dobrze pamietam to Woo zapisuje przy zdjeciu ze stocka ze towar zostal zdjety i przy przywroceniu ze zostal przywrocony w metadanych. Zaraz zobacze czy znajde ten fragment.

**Comment by PiotrCzapla** [comment]
tu ustawiaja te metadane na kazdym line item, przy redukcji stocka
https://github.com/woocommerce/woocommerce/blob/43f735d0f8cf8a82d10e5c5ba82e00db3faad8cd/includes/wc-stock-functions.php#L197

A tu usuwaja te metadane przy przywracaniu stocka
https://github.com/woocommerce/woocommerce/blob/43f735d0f8cf8a82d10e5c5ba82e00db3faad8cd/includes/wc-stock-functions.php#L295

Moze to kolizja w tych metadanych powoduje problem z nie udanymi zamowieniami?

**Comment by PiotrCzapla** [comment]
Po przemyśleniu sprawy to czy uzywanie "nieudane" jest wskazane? Może poprostu zamowienie powinno przejsc w stan Anulowane gdy nie powiedzie się platność, albo jak jest mozliwosc ponawiania platnosci to gdy klient zrezygnuje (time out po stronie paynow)?

Wtedy taki stan nie zmieniajacy stocka ma sens. Jak klient ma mozliwość zrobienia / ponowienia platności to stan zamowienia zostaje w oczekuje na platność z ewentualnymi komentarzami że platności kolejne sie nie powiodły etc. Po co przełączać na nieudane? jeżeli zamówienie może jeszcze zostać opłacone. Jak zostanie osiągnięty timeout to zamówienie nie opłacone powinno przejść na anulowane, w ten spób stock sie zmieni odpowiednio.

**Comment by PiotrCzapla** [comment]
ilość problemów z płatnościami się znacznie zmniejszyła wiec możemy zamknąć ten ticket. dzięki za poprawki
