### ISSUE TITLE
Klient opłaca zamówienie, pieniądze dochodzą, ale zamówienie dostaje status anulowane (jakby nie zostało opłacone)

### ISSUE THREAD

**Issue by gruntek** [pay-now/paynow-woocommerce#67]
Wszystkie zamówienia opłacone przez paynow nie zmieniają statusu na "w trakcie realizacji" - zamiast tego przechodzą na "anulowane" - pomimo iż płatność została dokonana prawidłowo i pieniądze dotarły na konto.

**Comment by emilleszczak2** [comment]
@gruntek 
1. Czy ustawiłeś poprawnie adres powiadomień w systemie paynow?
2. Czy masz włączone logi dla powiadomień?

Napisz proszę do nas na kontakt@paynow.pl z informacjami jakich transakcji to dotyczy.

**Comment by michalskladanowski** [comment]
Należy skonfigurować adres powiadomień zgodnie z instrukcją:
`W panelu sprzedawcy Paynow przejdź do zakładki Ustawienia > Sklepy i punkty płatności, w polu Adres powiadomień ustaw adres: https://twoja-domena.pl/?wc-api=WC_Gateway_Pay_By_Paynow_PL.`

**Comment by dominiksajdak** [comment]
Mam to samo, status po płatności jest "oczekuje na płatność" i po 60 minutach anuluje. Usunąłem ten limit 60 minut w ustawieniach woocommerce, ale to oczywiście problemu nie rozwiązuje. Jest jakiś problem z wiadomością powrotną do sklepu. Adres powiadomień wg instrukcji. Powiadomienia w woocommerce generalnie działają i pojawia się powiadomienie o anulowaniu z powodu braku płatności.

**Comment by gruntek** [comment]
> @gruntek
> 
> 1. Czy ustawiłeś poprawnie adres powiadomień w systemie paynow?
> 2. Czy masz włączone logi dla powiadomień?
> 
> Napisz proszę do nas na [kontakt@paynow.pl](mailto:kontakt@paynow.pl) z informacjami jakich transakcji to dotyczy.

@emilleszczak2 
ad 1. Tak, zgodnie z instrukcją.
ad 2. Nie, dopiero teraz włączyłem.

Napisałem wiadomość mailową.

**Comment by dominiksajdak** [comment]
Adresy powiadomień się same uzupełniają w mBanku. Sam mi się wpisał przy starszej wtyczce i sam mi się zmienił przy nowej wtyczce.

**Comment by emilleszczak2** [comment]
@gruntek 
Jeśli używasz wtyczki w wersji 2.0.0, to adres powiadomień powinien być w formacie: `https://domena/?wc-api=WC_Gateway_Pay_By_Paynow_PL`

Dla wersji wcześniejszej: `https://domena/?wc-api=WC_Gateway_Paynow`

**Comment by mmiszy** [comment]
@emilleszczak2 dzięki wielkie. Mogliście o tym wspomnieć w changelogu ;)

**Comment by mmiszy** [comment]
Mam ten sam problem. Adres powiadomień sam się ustawił na nowszy po aktualizacji wtyczki, jednak potwierdzenie płatności nie działa.

**Comment by PiotrCzapla** [comment]
@emilleszczak2  tu by sie swietnie nadawał stan nie udane. Wtedy stock by był zmieniony i czekało by na oblsugę sklepu z decyzją czy przywracac na stock bo rzeczywiscie klient nie oplacił (stan anulowane), czy procesować bo nie przyszła notyfikacjia.

**Comment by jwywiol** [comment]
Witam, mam ten sam problem, ale nie jest to regułą. Pieniądze kilku klientów przyszły na konto, a w zamówieniu mniej więcej po godzinie status zmienia się na anulowany: [screen](https://snipboard.io/dw7xZC.jpg)
Obecnie ręcznie sprawdziliśmy i zmieniliśmy status opłaconych zamówień. Co można zrobić, aby problem nie powrócił?
Testowe zamówienia przechodzą bez problemów...

**Comment by emilleszczak2** [comment]
@jwywiol 

Napisz proszę do nas na kontakt@paynow.pl (lub podaj tutaj identyfikator płatności) z informacjami jakich transakcji to dotyczy.

**Comment by PiotrCzapla** [comment]
@jwywiol  stan mogl sie zmienic na anulowane bo to woocomerce po pewnym czasie anuluje zamowienia oczekujace na platnosc, wydluzcie sobie czas oczekiwania bo pewnie macie krotki. Tu jest info jak to zmienic:
https://hitusupdesigns.com/wp-content/uploads/2015/12/Woocommerce-Fix.jpg
