### ISSUE TITLE
Panowie od kilku dni wysyp  wstrzymane oczekujące na płatność, a zamowienia opłacone

### ISSUE THREAD

**Issue by rafaljosko** [pay-now/paynow-woocommerce#68]
Klient płaci, pieniądze trafiają na konto, status zmieniany na zrealizowane, a następnie po minucie zamowienie przechodzi w status oczekujące na płatność. 

![image](https://user-images.githubusercontent.com/33252062/105001348-e9f45a00-5a2f-11eb-8493-c26724ad7bd4.png)

**Comment by emilleszczak2** [comment]
@rafaljosko Prośba o kontakt na support@paynow.pl z podaniem numeru płatności. W tytule proszę podać że chodzi o zgłoszenie na Githubie.

**Comment by rafaljosko** [comment]
Poszło, szkoda, że jakiegoś systemu ticketowego nie macie.

**Comment by emilleszczak2** [comment]
@rafaljosko Mamy, właśnie do niego napisałeś :)

**Comment by PiotrCzapla** [comment]
ja napisze tez bo mi paynow zwrocone zamowienie z 13 listopada wlasnie wczoraj 27 stycznia zamienił na 'oczekuje na platność', i przywrócił na stan jedną z roślin której nie mamy a była chodliwa wiec sie sprzedała po 10 min. :(

**Comment by rafaljosko** [comment]
Tak dzieje się to dość często - dziś mi dało na oczekuje na płatność zamówienie z przed kilku miesięcy.

**Comment by emilleszczak2** [comment]
@PiotrCzapla Podaj proszę numer płatności. Moduł sam z siebie nie zmienia stanów chyba, dzieje się tak dopiero gdy dostanie powiadomienie o stanie z systemu paynow. Sprawdzę co się działo z ta płatnością, bo nie powinno się tak zdarzyć.

**Comment by mancer81** [comment]
Potwierdzam problem. Choćby przed chwilą NO3Q-76A-7SC-0BX
Zgłaszałem już wcześniej na support@paynow.pl ale na razie cisza.

**Comment by emilleszczak2** [comment]
@mancer81 Przejście w status Nieudane (failed) jest realizowane przez wtyczkę w Paynow w momencie kiedy dostanie powiadomienie ze statusem REJECTED lub ERROR, żaden z nich nie został wysłany dla tej płatności.

Czy posiadasz włączony zapis logów dla wtyczki?

Widzę na screenie, że posiadasz wtyczkę o nazwie `Statusy zamówień`. Co ona robi? Czy to ona nie zmienia statusów automatycznie po jakimś czasie?

**Comment by mancer81** [comment]
> @mancer81 Przejście w status Nieudane (failed) jest realizowane przez wtyczkę w Paynow w momencie kiedy dostanie powiadomienie ze statusem `REJECTED` lub `ERROR`, żaden z nich nie został wysłany dla tej płatności.

Być może była to inna płatność dla tego zamówienia? I dopiero kolejna klientowi przeszła.

> Czy posiadasz włączony zapis logów dla wtyczki?

Nie, dopiero włączyłem.

> Widzę na screenie, że posiadasz wtyczkę o nazwie `Statusy zamówień`. Co ona robi? Czy to ona nie zmienia statusów automatycznie po jakimś czasie?

Statusy zamówień by WP Desk. Zmienia status na "zrealizowane" po otrzymaniu płatności jeśli w zamówieniu są tylko produkty wirtualne. Nie zmienia "po jakimś czasie".

Generalnie wcześniej wszystko przez lata stało w takiej konfiguracji na dotpay i nigdy nie było takich problemów.

**Comment by emilleszczak2** [comment]
@mancer81 Znalazłem pewien trop, możesz podesłać jeszcze inny numer płatności z która był taki sam problem?

**Comment by rafaljosko** [comment]
NOY8-TCO-2AZ-4DJ  - Ja tych zamówień mam pod dostatkiem :)

**Comment by rafaljosko** [comment]
> > @mancer81 Przejście w status Nieudane (failed) jest realizowane przez wtyczkę w Paynow w momencie kiedy dostanie powiadomienie ze statusem `REJECTED` lub `ERROR`, żaden z nich nie został wysłany dla tej płatności.
> 
> Być może była to inna płatność dla tego zamówienia? I dopiero kolejna klientowi przeszła.
> 
> > Czy posiadasz włączony zapis logów dla wtyczki?
> 
> Nie, dopiero włączyłem.
> 
> > Widzę na screenie, że posiadasz wtyczkę o nazwie `Statusy zamówień`. Co ona robi? Czy to ona nie zmienia statusów automatycznie po jakimś czasie?
> 
> Statusy zamówień by WP Desk. Zmienia status na "zrealizowane" po otrzymaniu płatności jeśli w zamówieniu są tylko produkty wirtualne. Nie zmienia "po jakimś czasie".
> 
> Generalnie wcześniej wszystko przez lata stało w takiej konfiguracji na dotpay i nigdy nie było takich problemów.

Nie musisz używać wtyczki wpdesku - dajesz produkt wirtualny  i do pobrania i w woocommerce w ustawieniach zmieniasz opcję- Przyznaj dostęp do produktów do pobrania po zrealizowaniu płatności

**Comment by emilleszczak2** [comment]
@rafaljosko dzięki

Trop jest taki, że do jednego zamówienia było wiele płatości - tutaj masz rację. Pierwsza płatność się nie udała, Klient ponowił (tworząc nową) gdzie autoruzacja była poprawna.

W przypadku płatności podanej przez Ciebie to jest inna kwestia. Podeślij proszę zrzut zapisu notatek do zamówienia.

**Comment by rafaljosko** [comment]
![image](https://user-images.githubusercontent.com/33252062/106729387-b4459880-660d-11eb-9203-3284612da29b.png)

**Comment by rafaljosko** [comment]
Ps. Mogę powiedzieć tylko tyle, że w starej wersji wtyczki przed 2.0 nie ma tego problemu - testowałem i jest wszystko ok

**Comment by mancer81** [comment]
> @mancer81 Znalazłem pewien trop, możesz podesłać jeszcze inny numer płatności z która był taki sam problem?

Szczegóły: Zamówienie #60702
Płatność przez: Zapłać z paynow.pl (NOEZ-RDT-UV1-KVL). Opłacone 22 stycznia 2021 o 08:33. Adres IP klienta: 83.22.97.234

**Comment by emilleszczak2** [comment]
@mancer81 ta sama sytuacja: Pierwsza płatność się nie udała, Klient ponowił (tworząc nową) gdzie autoryzacja była poprawna.

Dokonam modyfikacji we wtyczce aby nie przetwarzał powiadomienia jeśli zamówienie jest już oznaczone jako opłacone lub zakończone.
Zmodyfikuję treść notatek aby to było również widać, że dotyczą różnych płatności.

**Comment by emilleszczak2** [comment]
Nowa wersja: https://github.com/pay-now/paynow-woocommerce/releases/latest

**Comment by Stolarkonar** [comment]
Dzisiaj spotkałem się dokładnie z tym samym problemem i chyba już wiem z czego może on wynikać. Miałem wcześniej ustawionego providera z tPay i tam w ustawieniach była opcja „Automatycznie oznaczaj zamówienia jako zrealizowane”, to oznacza że niejako pomija status „w trakcie realizacji”. Ja np, nie korzystam ze statusu w trakcie realizacji, bo u mnie jest coś albo oczekujące na płatność (przy szybkich płatnościach) albo wstrzymane przy płatnościach za przelew albo completed (zrealizowane) jeśli dane płatności zostały zaksięgowane.

Podejrzewam, że to z tego może wynikać dany problem
