### ISSUE TITLE
Cloudflare i paynow

### ISSUE THREAD

**Issue by pawelpecak** [pay-now/paynow-woocommerce#76]
Kiedyś konfigurowałem płatności przez paynow i trafiłem na problem z odbieraniem statusu płatności ponieważ cloudflare blokował odpowiedź z tym statusem.

Czy może ktoś podać numer IP, z którgo paynow wysyła odpowiedź ze statusem transakcji zarówno dla środowiska produkcyjnego jak i sandbox?

Myślę, że to ułatwi życie ludziom, którzy zmagają się z brakiem aktualizacji statusów płatności blokowanych przez CF.

**Comment by michalskladanowski** [comment]
Przesyłam listę adresów IP do odblokowania:
prod: 40.119.155.18, 20.71.11.216
sandbox: 51.105.232.82, 51.105.232.90, 20.73.235.198.

W razie dalszych problemów z odbieraniem powiadomień prosimy o kontakt na adres: support@paynow.pl
