### ISSUE TITLE
Ikony płatności

### ISSUE THREAD

**Issue by lilkaparty** [pay-now/paynow-woocommerce#77]
Witam. Da radę dodać płatność blikiem jako osobny sposób płatności, ale wciąż korzystający z Paynow? Jeśli nie, to może da radę dodać chociaż ikony Blika i kart płatności?

**Comment by emilleszczak2** [comment]
@lilkaparty pracujemy nad wydzieleniem sposobów płatności

**Comment by emilleszczak2** [comment]
@lilkaparty najnowsza wersja (2.2.2) #88  umożliwia wydzielenie metod płatności.

**Comment by lilkaparty** [comment]
@emilleszczak2 ale to już w poprzedniej wersji było. Tak czy inaczej dzięki!
