### ISSUE TITLE
Wtyczka nie aktualizuje statusu zamówienia

### ISSUE THREAD

**Issue by deveropl** [pay-now/paynow-woocommerce#78]
Zamówienie złożone pieniądze klient płaci, dostaje potwierdzenie zapłaty od PAYNOW, ale w sklepie status zamówienia nadal zostaje. OCZEKUJE NA PŁATNOŚĆ.
brak informacji w panelu że zamówienie zapłacone

proszę o pomoc,
przykładowy identyfikaror płatnosci NO7C-N42-ZGO-HY4
sytuacja powtaż a się za każdym razem.
WOOCOMERCE 5.1.0

**Comment by emilleszczak2** [comment]
Ustawiony adres powiadomień jest niepoprawny (https://twoja-domena.pl/?wc-api=WC_Gateway_Pay_By_Paynow_PL - to jest tylko przykład a nie realna wartość)

**Comment by TheWojtek** [comment]
Jaka powinna być odpowiedź serwera na wywołanie https://wiem_ze_tutaj_moja_domena.pl/?wc-api=WC_Gateway_Pay_By_Paynow_PL ?
Mam dokładnie taką samą sytuację z prawidłowo ustawioną domeną i zastanawiam się, czy nie trzeba jakoś whitelistować zapytań do wc-api w pluginach zabezpieczających (choć inne usługi rozmawiające z API wordpressa działają)

**Comment by emilleszczak2** [comment]
@TheWojtek jeśli zezwalasz na cały ruch to powinieneś zobaczyć 400 Bad Request dla POST z błędnym lub brakiem body.
