### ISSUE TITLE
Nowa wersja 2.2.0  -konflikt z wtyczką eform 

### ISSUE THREAD

**Issue by rafaljosko** [pay-now/paynow-woocommerce#82]
Konflikt z wtyczką eForm - WordPress Form Builder 

- Puli Factory is not available
- No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: Http\Discovery\Strategy\CommonClassesStrategy::buzzInstantiate.
- No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: .

in /home/------/ftp/wp-content/plugins/wp-fsqm-pro/vendor/php-http/discovery/src/Exception/DiscoveryFailedException.php:41
Stack trace:
#0 /home/-------/ftp/wp-content/plugins/wp-fsqm-pro/vendor/php-http/discovery/src/ClassDiscovery.php(79): Http\Discovery\Exception\DiscoveryFailedException::create(Array)
#1 /home/---------/ftp/wp-content/plugins/wp-fsqm-pro/vendor/php-http/discovery/src/Psr18ClientDiscovery.php(25): Http\Discovery\ClassDisc

**Comment by emilleszczak2** [comment]
@rafaljosko Jest to wtyczka komercyjna. Masz do niej plik composer.json ?

**Comment by emilleszczak2** [comment]
@BlackWebWolf 
Czy wersja z przed 3 miesięcy 2.1.0 też się gryzie? Zależności na pierwszy rzut oka są te same.
Możliwe że zaszły jakieś miany w OrbiFox, które to powodują.

**Comment by BlackWebWolf** [comment]
> @BlackWebWolf
> Czy wersja z przed 3 miesięcy 2.1.0 też się gryzie? Zależności na pierwszy rzut oka są te same.
> Możliwe że zaszły jakieś miany w OrbiFox, które to powodują.

Nie, własnie wersja 2.1.0 nie ma problemu, po zrobieniu reverta do niższej wersji działa poprawnie, wraz z podbitą wersja OrfitFox

**Comment by emilleszczak2** [comment]
@BlackWebWolf prawdopodobą przyczyną problemów z działaniem sklepu jest ponownie konflikt z biblioteką dla mailerlie która wykorzystuje stare wersje bibliotek. Poniżej wyciąg z composer.lock dla Orbit Fox

```
{
            "name": "codeinwp/themeisle-content-forms",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/Codeinwp/themeisle-content-forms.git",
                "reference": "82d5f1d3c8617a5200f0e3f909a112da9dbd9926"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/Codeinwp/themeisle-content-forms/zipball/82d5f1d3c8617a5200f0e3f909a112da9dbd9926",
                "reference": "82d5f1d3c8617a5200f0e3f909a112da9dbd9926",
                "shasum": ""
            },
            "require": {
                "mailerlite/mailerlite-api-v2-php-sdk": "^0.2.3"
            },
            "require-dev": {
                "dealerdirect/phpcodesniffer-composer-installer": "^0.5.0",
                "wptrt/wpthemereview": "*"
            },
            "default-branch": true,
            "type": "library",
            "autoload": {
                "files": [
                    "load.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "GPL-3.0-or-later"
            ],
            "authors": [
                {
                    "name": "ThemeIsle",
                    "email": "friends@themeisle.com",
                    "homepage": "https://themeisle.com"
                }
            ],
            "description": "ThemeIsle Content Forms.",
            "homepage": "https://github.com/Codeinwp/themeisle-content-forms",
            "support": {
                "issues": "https://github.com/Codeinwp/themeisle-content-forms/issues",
                "source": "https://github.com/Codeinwp/themeisle-content-forms/tree/master"
            },
            "time": "2020-12-17T15:43:50+00:00"
        },
```

**Comment by rafaljosko** [comment]
@emilleszczak2  Zgada się można zamknąć :)
