### ISSUE TITLE
w wersji 2.2 nie mogę wybrać banku dla szybkiej płatności

### ISSUE THREAD

**Issue by pawelpecak** [pay-now/paynow-woocommerce#83]
Wczoraj zaktualizowałem wtyczkę w dwóch niezależnych sklepach i w obu występuje ten sam problem. Wybierając płatność paynow nie mogę zaznaczyć żadnego banku - wszystkie są "nieklikalne" a przycisk "Kupuję i płacę" jest nieaktywny
![Screenshot 2021-05-07 14 42 43](https://user-images.githubusercontent.com/75394496/117451342-b4be3a00-af42-11eb-8097-427a7facda11.png)

**Comment by emilleszczak2** [comment]
Czy możesz podać adres sklepu?

**Comment by pawelpecak** [comment]
tak, możesz to sprawdzić tutaj: [sklep](https://kursy.akademiaszpilek.pl/zamowienie/?add-to-cart=40)

**Comment by pawelpecak** [comment]
wyłączyłem Autoptimize i WP Super Cache aby nie ingerowały w plugin, ale problem nie ustąpił

**Comment by rafaljosko** [comment]
z tego co widzę jest to neve

**Comment by pawelpecak** [comment]
tak, w tym sklepie jest Neve, w innym [Elessi](https://themeforest.net/item/elessi-woocommerce-ajax-wordpress-theme/20968615) ale problem jest taki sam. Na jakim motywie testowałeś i działało? Spróbuję przetestować ten sam

**Comment by emilleszczak2** [comment]
Weryfikowałem na szablonie Shopper oraz standardowym Twenty Nineteen. Podpiąłem Neve i też jest OK z klikalnością
![image](https://user-images.githubusercontent.com/2837751/117613725-9dac6180-b167-11eb-9da3-f7533857c72d.png)

**Comment by emilleszczak2** [comment]
@pawelpecak Zmieniłem sposób prezentacji w nowej wersji [2.2.1 ](https://github.com/pay-now/paynow-woocommerce/releases/tag/2.2.1). Daj znać czy pomogło

**Comment by pawelpecak** [comment]
tak, teraz już można zaznaczyć odpowiedni banki i wykonać płatność. Dziękuję za pomoc

**Comment by emilleszczak2** [comment]
Dzięki, zamykam
