### ISSUE TITLE
2.2.1 nie można złożyć zamówienia przy powtórnym wybraniu płantości szybkim przelewem

### ISSUE THREAD

**Issue by PiotrCzapla** [pay-now/paynow-woocommerce#86]
Dzień dobry. Problem jest pokazany na załączonym screenshocie.  Wybrany jest mbank ale nie da sie złożyć zamówienia. 

Aby zreplikować problem wystarczy:
- wybrać szybki przelew, zaznaczyć bank
- wybrać blik
- wybrać szybki przelew - bank już jest zaznaczony ale przycisk złóż zamówienie nie jest włączony.

Dodatkowo miałbym dwie prośby:
1). Jak musicie mieć wybór banku na stronie z zamówieniem ktróra i tak jest juz przeładowana, to dobrze byłoby być zgodnym w obsłudze błędów z woo commerce, który zawsze pozwala kliknąć 'zlóż zmówienie' ale jak coś jest nie tak to pokazuje komunikat że należy coś poprawić. Robienie przycisku z zamówieniem nie aktywnym będzie trudne do zrozumienia przez moich klientów co obnizy nam konwersje we sklepie.
Wiec jak musicie mieć walidacje to starałbym się a by była zgodna z walidacją innych pół. Ale byłbym za tym żeby tej walidacji nie było przy nie wybranym przelewie aby pojawiał sie screen paynow z możliwością wyboru.

2). Ekran woocommerce jest już wystarczająco skomplikowany dodawani dużego pola z logo wszystkich banków robi ten ekran jeszcze bardziej skomplikowanym. Czy była by taka możliwość aby pokazać rożne typy płatności paynow (blik, szybkie przelewy, karta) ale aby nie wymagać wyboru typu szybkiego przelewu? Tak aby nie pojawiał się taki duży screen ze wszystkim bankami. 
Wtedy problem 1 się rozwiąże.

Ewentualnie jak nie da się zmienić jak działają stare przelewy to czy moglibyście dodać do konfiguracji (lub kodu) możliwość włączenia starego trybu działania? 

<img width="480" alt="Screenshot 2021-05-10 at 11 33 24" src="https://user-images.githubusercontent.com/340180/117641531-8df04580-b186-11eb-86d2-afaf57afe166.png">

**Comment by PiotrCzapla** [comment]
Cześc, nie chciałem krytykować nowego designu. Pomysł podziału sposobu płatności na typy jest dobry, bo mało osób kojarzy paynow, a jak widzą 'płatność blik' 'płatność  przelewem.. ' to odrazu rozumieją o co chodzi.

Chciałem wam zwrócić uwagę, że wyłączanie przycisku 'kupuje' to nie jest dobry pomysł na zrobienie pola wymaganym, bo jest inny niż większość pluginów woo. 

Druga sprawa to czy każdy sklep chce mieć wszystkie banki wypisane na stronie z zakupem. 

Klient powracający zwykle i tak będzie korzystał z jednego typy transferu i to ten typ powinien się pokazywać, po co pokazywać wszystkie opcje. Klient który jest pierwszy raz też nie potrzebuje widzieć wszystkich obsługiwanych banków bo oferta zwykle jest taka sama. 

To na czym mi zależy to aby ilość nie potrzebnych informacji ograniczyć do minimum w pierwszym kroku w którym klient decyduje się na zakup. 
Inna sprawa, że mogę ukryć ten wybór banków css'em tylko żeby potem paynow działał w kolejnym kroku i pokazał możliowść wyboru

**Comment by lilkaparty** [comment]
@PiotrCzapla obecne rozwiązanie jest super, zresztą sam o nie prosiłem. Klienci od razu widzą i mogą wybrać swoją płatność czy swój bank. Ja chcę mieć wszystkie banki dostępne, bo niektórzy klienci korzystają z różnych banków. W Twoim przypadku potrzebna byłaby wtyczka, która pozwala klientowi zapisać ostatni/wybrany sposób płatności jako preferowany. Wtedy po prostu klient by zamawiał jednym przyciskiem, jak chociażby na Allegro.

Ale do meritum. U mnie podany problem nie występuje. Może dlatego, że korzystam z wtyczki, która odświeża koszyk przy zmianach. Albo może w nowej wersji już to poprawili.

**Comment by emilleszczak2** [comment]
@PiotrCzapla Wydaliśmy nową wersja z uwzględnioną sugestią dotyczącą blokady przycisku i komunikatem o błędzie.

**Comment by PiotrCzapla** [comment]
@lilkaparty jak mi podasz link do sklepu to mogę Ci nagrać filmik z tego jak zreplikować ten problem  za blokowanym przyciskiem. 
Klienci wcześniej też mogli wybrać bank ale było już po krytycznym momencie kiedy złożyli zamówienie. Ale owszem jakby pay now dorobił się zapamiętywania ostatnio wybranego sposobu płatności i ukrywał inne to problem się rozwiązała. Dla nas tez działa opcja pozostania przy poprzednim interfejsie. Odkąd zmieniłem nazwe paynow na: Szybki przelew lub BLIK (paynow) klienci chętniej w niego klikają. 

@emilleszczak2  Dzięki za info, zobaczę czy po poprawkach jestem wstanie zrobić upgrade i jak to wygląda. Jak długo będziecie wspierać poprzednią wersje z interfejsem który nie pokazuję listy wspieranych banków?

**Comment by PiotrCzapla** [comment]
Dzięki za poprawkę, rozwiązałeś problem zablokowanego przycisku. No i j jak dam BLIK jak pierwszy typ płatności to strona już nie wygląda tak zle, cały czas. byłbym z tym zeby zapisywać ostatnio wybrany rodzaj przelewu ale o tym możemy pogadac w #77
