### ISSUE TITLE
Nie działa z Woocomerce 5.3.0

### ISSUE THREAD

**Issue by sebastiankorybski** [pay-now/paynow-woocommerce#96]
Wtyczka jest włączona, nie widać jej w Ustawieniach / Płatności. Po kliknięciu w przycisku Zapisz zmiany w Ustawieniach / Płatności, pojawia się. Zmiana zakładki np. na Konta i prywatność i powrót do zakładki Płatności skutkuje ponownym zniknięciem. Kliknięcie w przycisk konfiguruj nic nie powoduje.

**Comment by rafaljosko** [comment]
Hej mamy ten sam problem z naszą wtyczką WooCommerce Fakturownia i PayNow -  To samo się dzieje gdy nasza wtyczka jest włączona i paynow - Problemem jest to, że metody płatności paynow są ładowane za późno - Np: nasza wtyczka już zdąży pobrać bramki płatności jakie są zarejestrowane w Woo a paynow dopiero po tym rejestruje swoje metody.

**Comment by sebastiankorybski** [comment]
Właśnie przetestowałem. Pomaga wyłączenie wtyczki Fakturownia. Czyli mamy konflikt wtyczek Fakturownia od WpHocus z wtyczką PayNow.

**Comment by rafaljosko** [comment]
Zejdź wersją paynow do 2.1.0  i wszystko wróci do normy.  - Szykujemy poprawkę, chodzi o to, że pobierając metody płatności woocommerce je  cache'uje, i robi to  zanim paynow zdąży zarejestrować metody płatności.  Przez co one się nie wyświetlają.

**Comment by emilleszczak2** [comment]
@rafaljosko Gdzie jest problem?

**Comment by rafaljosko** [comment]
@emilleszczak2  WooCommerce jest zbudowane tak, że cachuje metody płatności -   Wystarczy, że dowolna wtyczka zechce pobrać zarejestrowane metody płatności (get_available_payment_gateways) i woocommerce cachuje. Pomijając waszą, ponieważ rejestrujecie za późno. add_filter( 'woocommerce_payment_gateways',    powinniście dodać zaraz po załadowaniu wtyczki.

**Comment by emilleszczak2** [comment]
@rafaljosko zerknij tutaj https://github.com/pay-now/paynow-woocommerce/pull/101

**Comment by emilleszczak2** [comment]
@sebastiankorybski Wystawiliśmy nową wersję z poprawką o której wspominał @rafaljosko 
https://github.com/pay-now/paynow-woocommerce/releases/latest

**Comment by sebastiankorybski** [comment]
> @sebastiankorybski Wystawiliśmy nową wersję z poprawką o której wspominał @rafaljosko
> https://github.com/pay-now/paynow-woocommerce/releases/latest

Niestety ta wersja niczego nie zmienia, ponieważ mamy konflikt wtyczek Fakturownia i PayNow. Po aktualizacji nadal metody płatności są niewidoczne, ale tym razem wszystkie zniknęły :) Nawet płatność przelewem. Działa tylko wersja 2.10

**Comment by emilleszczak2** [comment]
@rafaljosko piłka po waszej stronie

**Comment by rafaljosko** [comment]
> @rafaljosko piłka po waszej stronie
Działamy :)

**Comment by rafaljosko** [comment]
WooCommerce Fakturownia 1.6.103 - Poprawa kompatybilności z bramką płatności Paynow   -  Wtyczka już działa poprawnie z Paynow

**Comment by stalica** [comment]
Niestety wciąż nie działa dla najnowszego WooCommerce i WooCommerce Fakturownia. Brak płatności w Checkout i w ustawieniach płatności. Rollback do 2.1.0 rozwiązuje problem.

**Comment by emilleszczak2** [comment]
@stalica Próbowałeś po wgraniu nowej wersji wyczyścić wpisy w bazie danych w tabeli wp_options dla paynow?

**Comment by rafaljosko** [comment]
@stalica   Jak wersja WooCommerce Fakturownia? -  z tego co testowaliśmy i otrzymaliśmy informację od klientów już wszystko powinno działać.

**Comment by stalica** [comment]
@rafaljosko mój błąd, byłem pewien, że mam najnowszą, a miałem 1.6.101, pobrałem 1.6.103 i działa. Dziękuję.
