### ISSUE TITLE
Paynow nie pozwala wylączyć niechcianej płatności

### ISSUE THREAD

**Issue by PiotrCzapla** [pay-now/paynow-woocommerce#97]
Nie moge wylaczyc platności kartą w paynow, za każdym razem jak wybiore wyłącz, płatności włączają się na nowo.

Płatności kartą zapewnia nam inna firma (stripe), nie chce tego zmieniac bo przy okazji dają nam apple pay i googlepay które wypełnienia nam adres dostawy.

Co moge zrobić żeby to naprawić?

**Comment by michalskladanowski** [comment]
Czy ma  Pan zainstalowaną najnowszą wersję wtyczki paynow? W wersji [2.2.5](https://github.com/pay-now/paynow-woocommerce/releases/tag/2.2.5) została wprowadzona poprawka mogąca rozwiązać ten problem.

**Comment by emilleszczak2** [comment]
@PiotrCzapla udało się rozwiązać problem poprzez pobranie nowej wersji?

**Comment by PiotrCzapla** [comment]
Tak nawet do 2.2.7 i niestety nie działa, co gorsza mieliście problem z blikiem i nie dało się go wyłączyć i teraz mamy wiszące transakcje :(

**Comment by emilleszczak2** [comment]
@PiotrCzapla Nie odnotowujemy takiego problemu na czystem Woo, być może powoduje to inna wtyczka.

Próba wyłączenia była poprzez wejście do edycji czy z opcji toggle ?

**Comment by PiotrCzapla** [comment]
Opcja toggle. Mam wersje staging na ktorej jest tak samo. Wylaczylem wszystkie wtyczki poza woo i paynow, problem się powtarza. Może to jakaś zaszlość w ustawieniach w bazie? Paynow mamy bardzo wczesnie.

**Comment by PiotrCzapla** [comment]
na staging problem rozwiazal sie jak sprobowalem wylaczyc wtyczke z karty konfiguracji platnosci.

Teraz dziala tu i tu.

**Comment by PiotrCzapla** [comment]
ta sama akcja na produkcji naprawila problem, wiec cos bylo w bazie nie tak.

**Comment by emilleszczak2** [comment]
dzięki za informacje
